spring:
  jpa:
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/shop?createDatabaseIfNotExist=true
    username: root
    password: Ss55539927
jwt:
  secret: f315f6dbec1e5b50f51e29551d83fab20d34c62e9b65e0bfac654dfb386c5f02